start-at-login = true

after-startup-command = [
    'exec-and-forget open --new /Applications/CopyQ.app',
    'exec-and-forget sketchybar',
    'exec-and-forget borders active_color=0xffffffff inactive_color=0xff494d64 width=8.0',
]

# Notify Sketchybar about workspace change
exec-on-workspace-change = ['/bin/bash', '-c',
    'sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE'
]
# Reference: https://github.com/i3/i3/blob/next/etc/config

# i3 doesn't have "normalizations" feature that why we disable them here.
# But the feature is very helpful.
# Normalizations eliminate all sorts of weird tree configurations that don't make sense.
# Give normalizations a chance and enable them back.
enable-normalization-flatten-containers = false
enable-normalization-opposite-orientation-for-nested-containers = false

accordion-padding = 30

# Mouse follows focus when focused monitor changes
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

# Possible values: tiles|accordion
default-root-container-layout = 'tiles'

# Possible values: horizontal|vertical|auto
# 'auto' means: wide monitor (anything wider than high) gets horizontal orientation,
#               tall monitor (anything higher than wide) gets vertical orientation
default-root-container-orientation = 'auto'

[gaps]
    inner.horizontal = 4
    inner.vertical =   4
    outer.left =       4
    outer.bottom =     35
    outer.top =        3
    outer.right =      4


# option is invalid on current version (?)
#automatically-unhide-macos-hidden-apps = false

[key-mapping]
    preset = 'qwerty'

#[exec.env-vars]
#    SH_FUZZMENU = "$HOME/dev/milwaukee/fuzzmenu.sh"

[mode.main.binding]
    # See: https://nikitabobko.github.io/AeroSpace/goodies#open-a-new-window-with-applescript
    #All possible modifiers: cmd, alt, ctrl, shift

    # alactritty
    #ctrl-cmd-enter=['''exec-and-forget osascript -e "do shell script \"/Applications/Alacritty.app/Contents/MacOS/alacritty &\"" ''', 'mode main']
    ctrl-cmd-enter=['exec-and-forget open -n "Applications/Alacritty.app"','mode main']

    # ghostty
    #ctrl-cmd-enter=['exec-and-forget open -n "Applications/Ghostty.app"','mode main']

    # launch new browser instance
    ctrl-cmd-shift-w = 'exec-and-forget open -n -a firefox'
    
    # launch new browser instance (incognito/private)
    ctrl-cmd-shift-i = 'exec-and-forget open -a firefox -n --args -private-window'

    # launch flameshot
    ctrl-cmd-x = 'exec-and-forget open -a /Applications/flameshot.app -n --args gui'

    # launch choose (dmenu/rofi)
    ctrl-cmd-d = '''exec-and-forget ls /Applications/ \
        /Applications/Utilities/ \
        /System/Applications/ \
        /System/Applications/Utilities/ \
        | grep '\.app$' \
        | sed 's/\.app$//g' \
        | choose \
        | xargs -I {} open -a "{}.app"'''

    # launch "milwaukee/fuzzmenu.sh"
    ctrl-cmd-shift-o = '''exec-and-forget open \
        -n /Applications/Alacritty.app \
        --args \
        --title FuzzMenu \
        --command /Users/tyler/dev/milwaukee/fuzzmenu.sh\
        '''

    # kill focused window
    ctrl-cmd-shift-q = 'close --quit-if-last-window'

    # i3 wraps focus by default
    ctrl-cmd-j =         'focus --boundaries-action wrap-around-the-workspace left'
    ctrl-cmd-k =         'focus --boundaries-action wrap-around-the-workspace down'
    ctrl-cmd-l =         'focus --boundaries-action wrap-around-the-workspace up'
    ctrl-cmd-semicolon = 'focus --boundaries-action wrap-around-the-workspace right'

    ctrl-cmd-shift-j = 'move left'
    ctrl-cmd-shift-k = 'move down'
    ctrl-cmd-shift-l = 'move up'
    ctrl-cmd-shift-semicolon = 'move right'

    # Consider using 'join-with' command as a 'split' replacement if you want to enable
    # normalizations
    ctrl-cmd-h = 'split horizontal'
    ctrl-cmd-v = 'split vertical'

    ctrl-cmd-f = 'fullscreen'

    ctrl-cmd-s = 'layout v_accordion' # 'layout stacking' in i3
    ctrl-cmd-w = 'layout h_accordion' # 'layout tabbed' in i3
    ctrl-cmd-e = 'layout tiles horizontal vertical' # 'layout toggle split' in i3

    ctrl-cmd-shift-space = 'layout floating tiling' # 'floating toggle' in i3

    # Not supported, because this command is redundant in AeroSpace mental model.
    # See: https://nikitabobko.github.io/AeroSpace/guide#floating-windows
    #alt-space = 'focus toggle_tiling_floating'

    # `focus parent`/`focus child` are not yet supported, and it's not clear whether they
    # should be supported at all https://github.com/nikitabobko/AeroSpace/issues/5
    # alt-a = 'focus parent'

    ctrl-cmd-1 = 'workspace 1'
    ctrl-cmd-2 = 'workspace 2'
    ctrl-cmd-3 = 'workspace 3'
    ctrl-cmd-4 = 'workspace 4'
    ctrl-cmd-5 = 'workspace 5'
    ctrl-cmd-6 = 'workspace 6'
    ctrl-cmd-7 = 'workspace 7'
    ctrl-cmd-8 = 'workspace 8'
    ctrl-cmd-9 = 'workspace 9'
    ctrl-cmd-0 = 'workspace 10'

    ctrl-cmd-shift-1 = 'move-node-to-workspace 1'
    ctrl-cmd-shift-2 = 'move-node-to-workspace 2'
    ctrl-cmd-shift-3 = 'move-node-to-workspace 3'
    ctrl-cmd-shift-4 = 'move-node-to-workspace 4'
    ctrl-cmd-shift-5 = 'move-node-to-workspace 5'
    ctrl-cmd-shift-6 = 'move-node-to-workspace 6'
    ctrl-cmd-shift-7 = 'move-node-to-workspace 7'
    ctrl-cmd-shift-8 = 'move-node-to-workspace 8'
    ctrl-cmd-shift-9 = 'move-node-to-workspace 9'
    ctrl-cmd-shift-0 = 'move-node-to-workspace 10'

    ctrl-cmd-shift-c = 'reload-config'

    ctrl-cmd-shift-r = 'mode resize'

    ctrl-cmd-shift-m = 'mode movedisplay'

[mode.resize.binding]
    h = 'resize width -50'
    j = 'resize height +50'
    k = 'resize height -50'
    l = 'resize width +50'
    enter = 'mode main'
    esc = 'mode main'

# issue: missing up/down/left/right
[mode.movedisplay.binding]
   h = ['move-workspace-to-monitor left', 'mode main']
   j = ['move-workspace-to-monitor down', 'mode main']
   k = ['move-workspace-to-monitor up', 'mode main']
   l = ['move-workspace-to-monitor right', 'mode main']
   enter = 'mode main'
   esc = 'mode main'

# enable floating window for fuzzmenu.sh
[[on-window-detected]]
    if.app-id = 'org.alacritty'
    if.window-title-regex-substring = 'FuzzMenu'
    run = ['layout floating']
